main:
  - name: Bienvenue
    url: "#tf-home"
    weight: 10
  - name: Thérapeutes
    url: "#tf-team"
    weight: 20
  - name: Thérapies
    url: "#tf-services"
    weight: 30
  - name: Ressources
    url: "#tf-clients"
    weight: 40
  - name: Articles
    url: "#tf-works"
    weight: 50
  - name: Contact
    url: "#tf-contact"
    weight: 60
