name = "CNL Spirit"
license = "MIT"
description = "Theme developed for CNL, originally based on Spirit8"
tags = ["responsive", "one-page", "portfolio"]
features = ["configurable navigation", "configurable homepage"]
min_version = "0.165.0"

[author]
  name = "Nicolas Jeanmonod"
  homepage = "https://jeanmonod.net/"

[original]
  name = "Spirit8"
  homepage = "https://dribbble.com/shots/1907471-Freebie-Spirit8-HTML-Template"
